import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { loadEvents, aggregate, dailyCounts } from '../src/collect.js';

// Writes one transcript file and returns the projects folder holding it.
function fixture(lines) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'cuc-'));
  fs.mkdirSync(path.join(dir, 'proj'));
  fs.writeFileSync(path.join(dir, 'proj', 's.jsonl'), lines.map((l) => JSON.stringify(l)).join('\n'));
  return dir;
}

const ts = '2026-03-10T10:00:00Z';
const user = (uuid, content, extra = {}) => ({ type: 'user', uuid, sessionId: 's1', timestamp: ts, message: { content }, ...extra });
const usage = { input_tokens: 10, output_tokens: 100, cache_creation_input_tokens: 5, cache_read_input_tokens: 1000 };
const assistant = (id, content, u = usage) => ({ type: 'assistant', sessionId: 's1', timestamp: ts, message: { id, model: 'claude-opus-4-5', usage: u, content } });

test('counts only typed prompts, once each', () => {
  const dir = fixture([
    user('u1', 'hello'),
    user('u1', 'hello'), // copied into a resumed session
    user('u2', [{ type: 'tool_result', content: 'ok' }]),
    user('u3', 'Caveat: generated by the system'),
    user('u4', 'meta', { isMeta: true }),
    user('u5', 'subagent', { isSidechain: true }),
  ]);
  assert.equal(loadEvents(dir).prompts.length, 1);
});

test('counts a response split over several lines once, keeping the largest usage', () => {
  const dir = fixture([
    assistant('m1', [{ type: 'text', text: 'a' }], { ...usage, output_tokens: 1 }),
    assistant('m1', [{ type: 'tool_use', id: 't1', name: 'Bash' }]),
    assistant('m1', [{ type: 'tool_use', id: 't1', name: 'Bash' }]),
  ]);
  const ev = loadEvents(dir);
  assert.equal(ev.responses.length, 1);
  assert.equal(ev.responses[0].usage.output_tokens, 100);
  assert.equal(ev.tools.length, 1);
});

test('subagent responses are kept for the cost but left out of the stats', () => {
  const dir = fixture([
    assistant('m1', [{ type: 'text', text: 'a' }]),
    { ...assistant('m2', [{ type: 'tool_use', id: 't9', name: 'Read' }]), isSidechain: true },
  ]);
  const ev = loadEvents(dir);
  assert.equal(ev.responses.length, 2);
  assert.equal(ev.tools.length, 0);
  assert.equal(aggregate(ev).responses, 1);
});

test('aggregates tokens, models, tools and streaks', () => {
  const day = (d) => new Date(`2026-03-${d}T10:00:00`);
  const stats = aggregate({
    prompts: [{ ts: day(10), session: 'a' }, { ts: day(11), session: 'a' }, { ts: day(13), session: 'b' }],
    responses: [
      { ts: day(10), session: 'a', model: 'claude-opus-4-5', usage },
      { ts: day(11), session: 'a', model: 'claude-sonnet-4-5', usage: { ...usage, output_tokens: 300 } },
    ],
    tools: [{ ts: day(10), name: 'Bash' }, { ts: day(10), name: 'mcp__github__get_me' }, { ts: day(11), name: 'Bash' }],
  });
  assert.equal(stats.sessions, 2);
  assert.equal(stats.prompts, 3);
  assert.equal(stats.activeDays, 3);
  assert.equal(stats.longestStreak, 2);
  assert.equal(stats.tokens.output, 400);
  assert.equal(stats.tokensTotal, 400 + 20 + 10 + 2000);
  assert.equal(stats.favoriteModel, 'claude-sonnet-4-5');
  assert.deepEqual(stats.topTools, [['Bash', 2], ['get_me', 1]]);
  assert.equal(stats.peakHour, 10);
});

test('range filters old events out', () => {
  const old = new Date(Date.now() - 60 * 86400e3);
  const stats = aggregate({ prompts: [{ ts: old, session: 'a' }, { ts: new Date(), session: 'b' }], responses: [] }, '30d');
  assert.equal(stats.prompts, 1);
  assert.equal(stats.sessions, 1);
});

test('dailyCounts groups prompts by local day', () => {
  const counts = dailyCounts({ prompts: [{ ts: new Date('2026-03-10T09:00:00') }, { ts: new Date('2026-03-10T18:00:00') }] });
  assert.equal(counts.get('2026-03-10'), 2);
});

test('missing folder gives empty results', () => {
  const ev = loadEvents(path.join(os.tmpdir(), 'does-not-exist-cuc'));
  assert.deepEqual(ev, { prompts: [], responses: [], tools: [] });
});
